wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.2
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1730669903.67282
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 76
      - 103
      2:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 76
      - 103
      3:
      - 7
      - 13
      - 23
      4: 3.8.10
      5: 0.16.2
      8:
      - 5
      13: linux-x86_64
    visualize:
      conf_mat:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/confusion_matrix/v1
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          stringSettings:
            title: ''
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: conf_mat_table
                fields: []
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: loss_val
      5: 1
      6:
      - 1
    - 1: 'accuracy val '
      5: 1
      6:
      - 1
    - 1: conf_mat_table._type
      5: 1
      6:
      - 1
    - 1: conf_mat_table.sha256
      5: 1
      6:
      - 1
    - 1: conf_mat_table.size
      5: 1
      6:
      - 1
    - 1: conf_mat_table.artifact_path
      5: 1
      6:
      - 1
    - 1: conf_mat_table._latest_artifact_path
      5: 1
      6:
      - 1
    - 1: conf_mat_table.path
      5: 1
      6:
      - 1
    - 1: conf_mat_table.ncols
      5: 1
      6:
      - 1
    - 1: conf_mat_table.nrows
      5: 1
      6:
      - 1
    - 1: lr-Adam
      5: 1
      6:
      - 1
    - 1: loss_comp_time_inside_training
      5: 1
      6:
      - 1
    - 1: loss
      5: 1
      6:
      - 1
    - 1: accuracy
      5: 1
      6:
      - 1
    - 1: misc_time_inside_training
      5: 1
      6:
      - 1
    - 1: training_step_time
      5: 1
      6:
      - 1
    - 1: train_loss_epoch
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
